config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'main/compose_email'
  post '/sendmail', to: 'main#send_email', as: 'send_email'
  root 'main#compose_email'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def compose_email
    
  end

  def send_email
    MyMailer.send_email(mail_params).deliver
    flash[:notice] = "Yay! The email is sent."
    redirect_to main_compose_email_path
  end

  private
  def mail_params
    params.permit(:email, :name, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SMail
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      - flash.each do |name, msg|
        .alert.fade.in
          %div{:class => "alert alert-#{name == 'notice' ? "info" : "danger"} fade in"}
            %button.close{"data-dismiss" => "alert"}
              ×
            %i.fa-fw.fa.fa-info
            %strong
              %info
                = name
            = raw(msg)
      = yield

app/views/main/compose_email.html.haml
.row
  .col-md-6.col-md-offset-3
    .well.well-sm
      = form_tag(send_email_path, method: "post", :class=>"form-horizontal") do
        %fieldset
          %legend.text-center Write to someone
          / Email input
          .form-group
            %label.col-md-3.control-label{:for => "email"} E-mail
            .col-md-9
              %input#email.form-control{:name => "email", :placeholder => "Your email", :type => "text"}/
          / Subject input
          .form-group
            %label.col-md-3.control-label{:for => "subject"} Subject
            .col-md-9
              %input#subject.form-control{:name => "subject", :placeholder => "What is the subject?", :type => "text"}/
          / Message body
          .form-group
            %label.col-md-3.control-label{:for => "message"} Your message
            .col-md-9
              %textarea#message.form-control{:name => "message", :placeholder => "Please enter your message here...", :rows => "5"}
          / Form actions
          .form-group
            .col-md-12.text-right
              %button.btn.btn-primary.btn-lg{:type => "submit"} Submit